name: API Deployement

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
env: 
  DOTNET_IMAGE: '${{ secrets.DOCKER_HUB_USERNAME }}/sample-app'
  DOTNET_TAG: sample-app
  DOTNET_VERSION: 8.0.100
  UBUNTU_VERSION: ubuntu-22.04

jobs: 
  
  build:
    
    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     ubuntu: ['ubuntu-22.04']
    #     dotnet: ['8.0.100']
    
    steps:
  
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version:  ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Build Docker image
      run: |
        pwd
        ls
        dotnet publish ./API-DOTNET.csproj /t:PublishContainer -r linux-x64

    - name: change image tag
      run: docker tag '${{ env.DOTNET_IMAGE }}' '${{ env.DOTNET_IMAGE }}':latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker
      run: docker push 'docker.io${{ env.DOTNET_IMAGE }}'
    
